# Generated by Django 5.0.3 on 2024-03-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='This is tech blog', max_length=255),
        ),
    ]
